package com.ugarsoft.chyma.iwin.utils;

/**
 * Created by Chyma
 * <p/>
 * on 5/7/2016.
 */
public enum Constant {
    IWIN_SHARED_PREFERENCES_NAME, REGISTERED_GCM, GCM_RED_ID, APPLIANCE, ANNOUNCEMENT, IS_ANNOUNCEMENT,
    APP_USER, PORTAL_USER_ROLE, POWER_NEWS,  FAQ, BILL, TOTAL_KWH, MONTHLY_BILL, PERCENT_CONTRIBUTION,
    UNREAD_NEWS_COUNT, UNREAD_ANNOUNCEMENT_COUNT, INTENT_FROM_NEWS, TOGGLE, NOTIFICATION_COUNT,
    LOAD_DB, NEW_NOTIF, LOADING_DATA
}
